import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { TopNav } from "@/components/layout/navigation/top-nav";
import { User } from "@/lib/validations/users";
import { TooltipProvider } from "@/components/ui/tooltip";
import { ThemeProvider } from "@/providers/theme-provider";
import { APP_NAME } from "@/lib/constants";

const roboto = Roboto({
  variable: "--font-roboto",
  weight: ["400", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: APP_NAME,
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user: User = {
    id: "8a77860870adf078d",
    email: "test@test.com",
    name: "Test User",
    role: ["user", "moderator", "admin"],
    profilePictureUrl: null,
    lastLoginAt: new Date(Date.now()),
    isActive: true,
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
  };

  return (
    <html lang="en">
      <body className={`${roboto.variable} antialiased bg-foreground`} suppressHydrationWarning>
        <ThemeProvider>
          <TooltipProvider>
            <TopNav user={user} />
            <main>{children}</main>
          </TooltipProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
